# Generated by Django 5.1.7 on 2025-12-25 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Current status of the connection', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the connection request was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the connection was last updated')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the connection was accepted', null=True)),
                ('rejected_at', models.DateTimeField(blank=True, help_text='When the connection was rejected', null=True)),
                ('receiver', models.ForeignKey(help_text='User who received the connection request', on_delete=django.db.models.deletion.CASCADE, related_name='received_connections', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='User who initiated the connection request', on_delete=django.db.models.deletion.CASCADE, related_name='sent_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'connections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', 'status'], name='connections_sender__951803_idx'), models.Index(fields=['receiver', 'status'], name='connections_receive_44aadd_idx'), models.Index(fields=['sender', 'receiver'], name='connections_sender__6e3715_idx'), models.Index(fields=['status', 'created_at'], name='connections_status_1bbefe_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('sender', models.F('receiver')), _negated=True), name='prevent_self_connection')],
            },
        ),
    ]
