# Generated by Django 5.2.1 on 2025-12-28 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_usercategory_user_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.usercategory'),
        ),
    ]
