# Generated by Django 5.2.1 on 2025-12-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_userprofile_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='updated_at',
        ),
    ]
