# Generated by Django 5.2.1 on 2026-01-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_userprofile_bio_userprofile_cover_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='level_of_education',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name_of_school',
            field=models.CharField(default='', max_length=50),
        ),
    ]
