# Generated by Django 5.2.1 on 2026-01-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_userprofile_level_of_education_and_more'),
        ('user', '0008_alter_article_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prefrence',
            name='category',
        ),
        migrations.AddField(
            model_name='prefrence',
            name='category',
            field=models.ManyToManyField(to='user.category', verbose_name='categories'),
        ),
    ]
