# Generated by Django 5.2.1 on 2026-02-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_prefrence_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='flags',
            field=models.IntegerField(default=0),
        ),
    ]
