# Generated by Django 5.2.1 on 2025-12-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
