# Generated by Django 5.2.1 on 2025-12-28 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_category_alter_article_title_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.article'),
        ),
    ]
