# Generated by Django 5.2.1 on 2026-01-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_comment_is_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
