# Generated by Django 5.2.1 on 2026-01-28 16:30

from django.db import migrations, models
from django.utils.text import slugify



class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
    # operations = [
    #     migrations.RunPython(populate_slugs),
    # ]
    
