# Generated by Django 5.2.1 on 2026-02-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(auto_created=True, max_length=255, unique=True),
        ),
    ]
