# Generated by Django 5.2.1 on 2026-02-14 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 14, 6, 35, 37, 262227, tzinfo=datetime.timezone.utc)),
        ),
    ]
